[package]
name = "p_p_instapaper"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
scraper = "0.13.0"
reqwest = "0.11.12"
anyhow = "1.0.66"
tokio = { version = "1.21.2", features = ["full"] }
